import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Navigation
 * Id: 621610c6-4c7a-4aa8-a2cb-f7f39a84c126
 * Codename: navigation
 */
export type Navigation = IContentItem<{
  /**
   * Navigation Options (multiple_choice)
   * Required: true
   * Id: 08bf0edc-6557-4ff4-8eb9-6857feb25184
   * Codename: navigation__untitled_multiple_choice
   */
  navigation__untitled_multiple_choice: Elements.MultipleChoiceElement;
}>;
