import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * SEO metadata
 * Id: 508cbaf0-0a75-43c5-9386-7c972ab55d82
 * Codename: seo_metadata_example_to_include_in_any_type
 */
export type SEOMetadata = IContentItem<{
  /**
   * Meta description (text)
   * Required: false
   * Id: a6d71176-bd66-42ae-92b1-9d1d4e2c8181
   * Codename: seo_metadata_example_to_include_in_any_type__meta_description
   *
   * This is a simple text field. It defines the description for your SEO metadata. Text fields don't store any formatting.
   */
  seo_metadata_example_to_include_in_any_type__meta_description: Elements.TextElement;

  /**
   * Meta title (text)
   * Required: false
   * Id: e295e0be-3d12-4fcc-b6b9-a308b7307bce
   * Codename: seo_metadata_example_to_include_in_any_type__meta_title
   *
   * This is a simple text field. It defines the title for your SEO metadata (and can be different than the name in Kontent.ai). Text fields don't store any formatting.
   */
  seo_metadata_example_to_include_in_any_type__meta_title: Elements.TextElement;
}>;
