import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Navigation } from '../content-type-snippets/navigation';

/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Article
 * Id: f4c46a4b-c929-4596-890b-178a635ac00d
 * Codename: article
 */
export type Article = IContentItem<{
  /**
   * Content (rich_text)
   * Required: true
   * Id: 91d587ac-4e2f-4e15-9d93-fc2e3ee039f9
   * Codename: content
   */
  content: Elements.RichTextElement;

  /**
   * Headline (text)
   * Required: true
   * Id: 3a42fecc-385f-4344-9dbf-13b5a78e26e1
   * Codename: headline
   */
  headline: Elements.TextElement;
}> &
  Navigation;
