import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Hero Banner
 * Id: 1b6ffc79-62ba-44b9-9062-67311152a54d
 * Codename: hero_banner
 */
export type HeroBanner = IContentItem<{
  /**
   * Background Image (asset)
   * Required: true
   * Id: 88d55ff3-dab2-4191-8139-10222742d879
   * Codename: background_image
   */
  background_image: Elements.AssetsElement;

  /**
   * CTA Route (text)
   * Required: false
   * Id: 15860e2c-0a28-4ff2-b112-071bffc1ac7b
   * Codename: cta_route
   */
  cta_route: Elements.TextElement;

  /**
   * CTA Text (text)
   * Required: false
   * Id: 24797d83-7c17-48ab-adb6-94c7f58bb194
   * Codename: cta_text
   */
  cta_text: Elements.TextElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: fb61d84c-4808-43c5-ba4d-475c9750690a
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Headline (text)
   * Required: true
   * Id: cb0db841-96c9-40a9-802c-ca4d21f67856
   * Codename: headline
   */
  headline: Elements.TextElement;
}>;
