import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type HeroBanner } from './hero_banner';
import { type Product } from './product';

/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Home Page
 * Id: e7559b68-9cd2-40cd-979f-aaa989a8a40c
 * Codename: home_page
 */
export type HomePage = IContentItem<{
  /**
   * Featured Products (modular_content)
   * Required: false
   * Id: 58aedb6e-5318-4850-9551-354a3093a041
   * Codename: feature_products
   */
  feature_products: Elements.LinkedItemsElement<Product>;

  /**
   * Hero (modular_content)
   * Required: true
   * Id: 9fa36ee5-0aef-45a3-bfae-40ecdf767294
   * Codename: hero
   */
  hero: Elements.LinkedItemsElement<HeroBanner>;
}>;
