import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Navigation } from '../content-type-snippets/navigation';
import { type Product } from './product';
import { type SEOMetadata } from '../content-type-snippets/seo_metadata_example_to_include_in_any_type';

/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Products
 * Id: ff9c3d68-a5df-4116-a14b-f92fcf99949c
 * Codename: products
 */
export type Products = IContentItem<{
  /**
   * Heading (text)
   * Required: true
   * Id: af07cd0c-df9e-4cc0-872e-66f8f74388dc
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Products (modular_content)
   * Required: true
   * Id: d2c04801-2beb-470b-90ea-59cf1d86115f
   * Codename: products
   */
  products: Elements.LinkedItemsElement<Product>;
}> &
  Navigation &
  SEOMetadata;
