import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type ProductCategories } from '../taxonomies/product_categories';

/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Product
 * Id: b3849622-03a6-4c76-b7e0-e3ba3f8a6bbd
 * Codename: product
 */
export type Product = IContentItem<{
  /**
   * Description (rich_text)
   * Required: true
   * Id: a5802466-c5ca-491e-9b29-c351067cbdf7
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Images (asset)
   * Required: true
   * Id: d6e98c7d-2bf8-4490-9e67-033cbdfef361
   * Codename: images
   */
  images: Elements.AssetsElement;

  /**
   * Name (text)
   * Required: true
   * Id: 1639e846-2fd7-44a9-978c-326fc5e19095
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * Price (number)
   * Required: true
   * Id: 988e918e-4f33-4f2b-98a1-1155a0f173ea
   * Codename: price
   */
  price: Elements.NumberElement;

  /**
   * Product Categories (taxonomy)
   * Required: true
   * Id: 7fe3443b-252f-4edb-8956-0a9e3ab944e1
   * Codename: product_categories
   */
  product_categories: Elements.TaxonomyElement<ProductCategories>;

  /**
   * Slug (url_slug)
   * Required: true
   * Id: 8cd885b7-312b-4a88-b6f8-2269595302ea
   * Codename: slug
   */
  slug: Elements.UrlSlugElement;
}>;
