/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Product Categories
 * Id: 0ef6587f-f6d9-48f9-9aba-853d6ddd40f8
 * Codename: product_categories
 */
export type ProductCategories = 'accessories' | 'clothing' | 'food';
