/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: NK Store Demo
 * Environment: Production
 * Project Id: 9d6858cd-ceea-0076-31e7-72c3266ce1fd
 */
export const assetFolders = {
  /**
   * Products
   */
  products: {
    id: 'b9b5321b-b6ff-458b-abf2-ec36995bc96a',
    name: 'Products',
    externalId: undefined,
    folders: {
      /**
       * Coffee
       */
      coffee: {
        id: 'af58d61d-cce6-4fb6-aad8-f7a4988bf663',
        name: 'Coffee',
        externalId: undefined,
        folders: {},
      },
    },
  },
} as const;
