/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: NK Store Demo
 * Environment: Production
 * Project Id: 9d6858cd-ceea-0076-31e7-72c3266ce1fd
 */
export const collections = {
  /**
   * Products
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Products',
  },
} as const;
