/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: NK Store Demo
 * Environment: Production
 * Project Id: 9d6858cd-ceea-0076-31e7-72c3266ce1fd
 */
export const contentTypeSnippets = {
  /**
   * Navigation
   * Last modified: Tue Nov 29 2022 09:55:01 GMT-0600 (Central Standard Time)
   */
  navigation: {
    codename: 'navigation',
    id: '621610c6-4c7a-4aa8-a2cb-f7f39a84c126',
    externalId: undefined,
    name: 'Navigation',
    elements: {
      /**
       * Navigation Options (multiple_choice)
       */
      navigation__untitled_multiple_choice: {
        codename: 'navigation__untitled_multiple_choice',
        id: '08bf0edc-6557-4ff4-8eb9-6857feb25184',
        externalId: undefined,
        name: 'Navigation Options',
        required: true,
        type: 'multiple_choice',
      },
    },
  },

  /**
   * SEO metadata
   * Last modified: Wed Dec 07 2022 13:54:35 GMT-0600 (Central Standard Time)
   */
  seo_metadata_example_to_include_in_any_type: {
    codename: 'seo_metadata_example_to_include_in_any_type',
    id: '508cbaf0-0a75-43c5-9386-7c972ab55d82',
    externalId: undefined,
    name: 'SEO metadata',
    elements: {
      /**
       * Meta title (text)
       *
       * This is a simple text field. It defines the title for your SEO metadata (and can be different than the name in Kontent.ai). Text fields don't store any formatting.
       */
      seo_metadata_example_to_include_in_any_type__meta_title: {
        codename: 'seo_metadata_example_to_include_in_any_type__meta_title',
        id: 'e295e0be-3d12-4fcc-b6b9-a308b7307bce',
        externalId: undefined,
        name: 'Meta title',
        required: false,
        type: 'text',
      },

      /**
       * Meta description (text)
       *
       * This is a simple text field. It defines the description for your SEO metadata. Text fields don't store any formatting.
       */
      seo_metadata_example_to_include_in_any_type__meta_description: {
        codename:
          'seo_metadata_example_to_include_in_any_type__meta_description',
        id: 'a6d71176-bd66-42ae-92b1-9d1d4e2c8181',
        externalId: undefined,
        name: 'Meta description',
        required: false,
        type: 'text',
      },
    },
  },
} as const;
