/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: NK Store Demo
 * Environment: Production
 * Project Id: 9d6858cd-ceea-0076-31e7-72c3266ce1fd
 */
export const languages = {
  /**
   * Default project language
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    isActive: true,
    isDefault: true,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'Default project language',
  },
} as const;
