/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: NK Store Demo
 * Environment: Production
 * Project Id: 9d6858cd-ceea-0076-31e7-72c3266ce1fd
 */
export const roles = {} as const;
