/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: NK Store Demo
 * Environment: Production
 * Project Id: 9d6858cd-ceea-0076-31e7-72c3266ce1fd
 */
export const taxonomies = {
  /**
   * Product Categories
   */
  product_categories: {
    codename: 'product_categories',
    id: '0ef6587f-f6d9-48f9-9aba-853d6ddd40f8',
    externalId: undefined,
    name: 'Product Categories',
    terms: {
      accessories: {
        codename: 'accessories',
        id: '88edaec4-5823-4cd0-8150-53427eb1d8b6',
        externalId: undefined,
        name: 'Accessories',
        terms: {},
      },
      clothing: {
        codename: 'clothing',
        id: '5c08f2fc-6885-43cf-a8b7-d82f3ca41eab',
        externalId: undefined,
        name: 'Clothing',
        terms: {},
      },
      food: {
        codename: 'food',
        id: 'ff641696-8d35-4c85-b447-9e9e56e4447e',
        externalId: undefined,
        name: 'Food',
        terms: {},
      },
    },
  },
} as const;
