/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: NK Store Demo
 * Environment: Production
 * Project Id: 9d6858cd-ceea-0076-31e7-72c3266ce1fd
 */
export const webhooks = {
  /**
   * GitHub
   * Last modified: Wed Nov 30 2022 15:05:13 GMT-0600 (Central Standard Time)
   */
  gitHub: {
    url: 'https://kontentaiwebhooks.azurewebsites.net/api/ContentPublished?code=3gccj_CHa5T9IktcKAnGCkTM8ayZ2Zgi6krxlxYXpau6AzFuu74kvw==',
    id: 'd0902ef4-a2a6-4a0d-a444-2e51769d8a21',
    name: 'GitHub',
  },
} as const;
